<?php

/**
 * BaseTipoLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Lugares
 * 
 * @method integer             getId()      Returns the current record's "id" value
 * @method string              getName()    Returns the current record's "name" value
 * @method Doctrine_Collection getLugares() Returns the current record's "Lugares" collection
 * @method TipoLugar           setId()      Sets the current record's "id" value
 * @method TipoLugar           setName()    Sets the current record's "name" value
 * @method TipoLugar           setLugares() Sets the current record's "Lugares" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipoLugar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_lugar');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Lugar as Lugares', array(
             'local' => 'id',
             'foreign' => 'tipo_lugar_id'));
    }
}