<?php

/**
 * BaseChofer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $telefono
 * @property integer $brevete
 * @property integer $empresa_id
 * @property Empresa $Empresa
 * @property Doctrine_Collection $Registro
 * @property Doctrine_Collection $Salida
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getTelefono()   Returns the current record's "telefono" value
 * @method integer             getBrevete()    Returns the current record's "brevete" value
 * @method integer             getEmpresaId()  Returns the current record's "empresa_id" value
 * @method Empresa             getEmpresa()    Returns the current record's "Empresa" value
 * @method Doctrine_Collection getRegistro()   Returns the current record's "Registro" collection
 * @method Doctrine_Collection getSalida()     Returns the current record's "Salida" collection
 * @method Chofer              setId()         Sets the current record's "id" value
 * @method Chofer              setName()       Sets the current record's "name" value
 * @method Chofer              setTelefono()   Sets the current record's "telefono" value
 * @method Chofer              setBrevete()    Sets the current record's "brevete" value
 * @method Chofer              setEmpresaId()  Sets the current record's "empresa_id" value
 * @method Chofer              setEmpresa()    Sets the current record's "Empresa" value
 * @method Chofer              setRegistro()   Sets the current record's "Registro" collection
 * @method Chofer              setSalida()     Sets the current record's "Salida" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseChofer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chofer');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('telefono', 'integer', 15, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('brevete', 'integer', 12, array(
             'type' => 'integer',
             'notnull' => true,
             'length' => '12',
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Registro', array(
             'local' => 'id',
             'foreign' => 'chofer_id'));

        $this->hasMany('Salida', array(
             'local' => 'id',
             'foreign' => 'chofer_id'));
    }
}