<?php

/**
 * BaseLugar
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $tipo_lugar_id
 * @property string $name
 * @property TipoLugar $TipoLugar
 * @property Doctrine_Collection $Registro
 * @property Doctrine_Collection $Salida
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method integer             getTipoLugarId()   Returns the current record's "tipo_lugar_id" value
 * @method string              getName()          Returns the current record's "name" value
 * @method TipoLugar           getTipoLugar()     Returns the current record's "TipoLugar" value
 * @method Doctrine_Collection getRegistro()      Returns the current record's "Registro" collection
 * @method Doctrine_Collection getSalida()        Returns the current record's "Salida" collection
 * @method Lugar               setId()            Sets the current record's "id" value
 * @method Lugar               setTipoLugarId()   Sets the current record's "tipo_lugar_id" value
 * @method Lugar               setName()          Sets the current record's "name" value
 * @method Lugar               setTipoLugar()     Sets the current record's "TipoLugar" value
 * @method Lugar               setRegistro()      Sets the current record's "Registro" collection
 * @method Lugar               setSalida()        Sets the current record's "Salida" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseLugar extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('lugar');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('tipo_lugar_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('TipoLugar', array(
             'local' => 'tipo_lugar_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Registro', array(
             'local' => 'id',
             'foreign' => 'lugar_id'));

        $this->hasMany('Salida', array(
             'local' => 'id',
             'foreign' => 'lugar_id'));
    }
}