<?php

/**
 * BaseOpciones
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $value
 * 
 * @method string   getName()  Returns the current record's "name" value
 * @method string   getValue() Returns the current record's "value" value
 * @method Opciones setName()  Sets the current record's "name" value
 * @method Opciones setValue() Sets the current record's "value" value
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseOpciones extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('opciones');
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
        $this->hasColumn('value', 'string', 255, array(
             'type' => 'string',
             'length' => '255',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}