<?php

/**
 * BaseTipoCarga
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $area_id
 * @property string $name
 * @property Area $Area
 * @property Doctrine_Collection $Registro
 * @property Doctrine_Collection $Salida
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method integer             getAreaId()   Returns the current record's "area_id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Area                getArea()     Returns the current record's "Area" value
 * @method Doctrine_Collection getRegistro() Returns the current record's "Registro" collection
 * @method Doctrine_Collection getSalida()   Returns the current record's "Salida" collection
 * @method TipoCarga           setId()       Sets the current record's "id" value
 * @method TipoCarga           setAreaId()   Sets the current record's "area_id" value
 * @method TipoCarga           setName()     Sets the current record's "name" value
 * @method TipoCarga           setArea()     Sets the current record's "Area" value
 * @method TipoCarga           setRegistro() Sets the current record's "Registro" collection
 * @method TipoCarga           setSalida()   Sets the current record's "Salida" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTipoCarga extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tipo_carga');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('area_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Area', array(
             'local' => 'area_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Registro', array(
             'local' => 'id',
             'foreign' => 'tipo_carga_id'));

        $this->hasMany('Salida', array(
             'local' => 'id',
             'foreign' => 'tipo_carga_id'));
    }
}