<?php

/**
 * BaseEmpresa
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property Doctrine_Collection $Choferes
 * @property Doctrine_Collection $Carretas
 * @property Doctrine_Collection $Tractos
 * @property Doctrine_Collection $Registro
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getName()     Returns the current record's "name" value
 * @method Doctrine_Collection getChoferes() Returns the current record's "Choferes" collection
 * @method Doctrine_Collection getCarretas() Returns the current record's "Carretas" collection
 * @method Doctrine_Collection getTractos()  Returns the current record's "Tractos" collection
 * @method Doctrine_Collection getRegistro() Returns the current record's "Registro" collection
 * @method Empresa             setId()       Sets the current record's "id" value
 * @method Empresa             setName()     Sets the current record's "name" value
 * @method Empresa             setChoferes() Sets the current record's "Choferes" collection
 * @method Empresa             setCarretas() Sets the current record's "Carretas" collection
 * @method Empresa             setTractos()  Sets the current record's "Tractos" collection
 * @method Empresa             setRegistro() Sets the current record's "Registro" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseEmpresa extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('empresa');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 40, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '40',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Chofer as Choferes', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Carreta as Carretas', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Tracto as Tractos', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));

        $this->hasMany('Registro', array(
             'local' => 'id',
             'foreign' => 'empresa_id'));
    }
}