<?php

/**
 * BaseTracto
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $placa
 * @property float $peso
 * @property string $configuracion
 * @property boolean $propia
 * @property integer $tara
 * @property string $tipo_unidad
 * @property integer $empresa_id
 * @property Empresa $Empresa
 * @property Doctrine_Collection $Registro
 * @property Doctrine_Collection $Salida
 * 
 * @method integer             getId()            Returns the current record's "id" value
 * @method string              getPlaca()         Returns the current record's "placa" value
 * @method float               getPeso()          Returns the current record's "peso" value
 * @method string              getConfiguracion() Returns the current record's "configuracion" value
 * @method boolean             getPropia()        Returns the current record's "propia" value
 * @method integer             getTara()          Returns the current record's "tara" value
 * @method string              getTipoUnidad()    Returns the current record's "tipo_unidad" value
 * @method integer             getEmpresaId()     Returns the current record's "empresa_id" value
 * @method Empresa             getEmpresa()       Returns the current record's "Empresa" value
 * @method Doctrine_Collection getRegistro()      Returns the current record's "Registro" collection
 * @method Doctrine_Collection getSalida()        Returns the current record's "Salida" collection
 * @method Tracto              setId()            Sets the current record's "id" value
 * @method Tracto              setPlaca()         Sets the current record's "placa" value
 * @method Tracto              setPeso()          Sets the current record's "peso" value
 * @method Tracto              setConfiguracion() Sets the current record's "configuracion" value
 * @method Tracto              setPropia()        Sets the current record's "propia" value
 * @method Tracto              setTara()          Sets the current record's "tara" value
 * @method Tracto              setTipoUnidad()    Sets the current record's "tipo_unidad" value
 * @method Tracto              setEmpresaId()     Sets the current record's "empresa_id" value
 * @method Tracto              setEmpresa()       Sets the current record's "Empresa" value
 * @method Tracto              setRegistro()      Sets the current record's "Registro" collection
 * @method Tracto              setSalida()        Sets the current record's "Salida" collection
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
abstract class BaseTracto extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('tracto');
        $this->hasColumn('id', 'integer', null, array(
             'primary' => true,
             'type' => 'integer',
             'autoincrement' => true,
             ));
        $this->hasColumn('placa', 'string', 8, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '8',
             ));
        $this->hasColumn('peso', 'float', null, array(
             'type' => 'float',
             'notnull' => true,
             ));
        $this->hasColumn('configuracion', 'string', 10, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '10',
             ));
        $this->hasColumn('propia', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             ));
        $this->hasColumn('tara', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('tipo_unidad', 'string', 15, array(
             'type' => 'string',
             'notnull' => true,
             'length' => '15',
             ));
        $this->hasColumn('empresa_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Empresa', array(
             'local' => 'empresa_id',
             'foreign' => 'id',
             'onDelete' => 'RESTRICT'));

        $this->hasMany('Registro', array(
             'local' => 'id',
             'foreign' => 'tracto_id'));

        $this->hasMany('Salida', array(
             'local' => 'id',
             'foreign' => 'tracto_id'));
    }
}