<?php

/**
 * Supervisor
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Supervisor extends BaseSupervisor
{
  public function getNombre()
  {
    return $this->getName()." ".$this->getLastName();
  }
}