#vision
vision:
  url:     /vision
  param:   { module: vision, action: index }

#registro
registrar:
  url:     /registrar
  param:   { module: registro, action: new }

registrar_create:
  url:     /registrar/create
  param:   { module: registro, action: create }

reload:
  url:     /reload
  param:   { module: registro, action: reload }

loaddata:
  url:     /loaddata
  param:   { module: registro, action: load }

#ingreso
ingreso:
  url:     /ingreso
  param:   { module: registro, action: index }

ingresar:
  url:     /ingresar/:id
  class:   sfDoctrineRoute
  options: { model: Registro, type: object }
  param:   { module: registro, action: ingreso }
  requirements:
    id: \d+
    sf_method: [get]

#operacion
operacion:
  class:   sfDoctrineRouteCollection
  options: { model: Operacion }

descarga:
  url:     /descarga
  class:   sfDoctrineRoute
  options: { model: Operacion, type: object }
  param:   { module: operacion, action: descarga }
  requirements:
    sf_method: [get]

carga:
  url:     /carga
  class:   sfDoctrineRoute
  options: { model: Operacion, type: object }
  param:   { module: operacion, action: carga }
  requirements:
    sf_method: [get]

inicio:
  url:     /inicio/:id
  class:   sfDoctrineRoute
  options: { model: Registro, type: object }
  param:   { module: operacion, action: inicio }
  requirements:
    id: \d+
    sf_method: [get]

detener:
  url:     /detener/:id
  class:   sfDoctrineRoute
  options: { model: Registro, type: object }
  param:   { module: operacion, action: edit }
  requirements:
    id: \d+
    sf_method: [get]

fin:
  url:     /fin
  param:   { module: operacion, action: update }

#salida
salida:
  url:     /salida
  param:   { module: salida, action: index }

salida_new:
  url:     /salida/:id
  class:   sfDoctrineRoute
  options: { model: Registro, type: object }
  param:   { module: salida, action: new }
  requirements:
    id: \d+
    sf_method: [get]

salida_create:
  url:     /salida/crear
  class:   sfDoctrineRoute
  options: { model: Registro, type: object }
  param:   { module: salida, action: create }
  requirements:
    sf_method: [post]

# default rules
homepage:
  url:   /
  param: { module: registro, action: new }