# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            2a317f708ecf2c49bfcc8145e9ed3bcb140f5d53

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true

    # Enable module
    enabled_modules:        [default, sfGuardAuth]

    # Default Culture
    default_culture:        es_ES

    # Standar Helpers
    standard_helpers:       [Partial, ysUtil, ysJQueryRevolutions]

  .actions:

    # Login modules
    login_module:           sfGuardAuth
    login_action:           signin

    # Secure modules
    secure_module:          sfGuardAuth
    secure_action:          secure