<?php

/**
 * Empresa
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Transporte
{
  static public $estado = array (
    0 => 'pendiente de INGRESO',
    1 => 'pendiente de DESCARGA',
    2 => 'proceso de decarga',
    3 => 'pendiente de CARGA',
    4 => 'proceso de carga',
    5 => 'pendiente de SALIDA',
    6 => 'concluyo',
  );
}