<?php

/**
 * Carreta
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    transporte
 * @subpackage model
 * @author     ejosvp
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class Carreta extends BaseCarreta
{
  public function __toString()
  {
    return (!is_null($this->getPlaca()) ? $this->getPlaca() : '' );
  }
  public function getUnidad()
  {
    return (!is_null($this->getTipoUnidad()) ? $this->getTipoUnidad() : '' );
  }
}